### ISSUE TITLE
Fabric 1.21 tool goes to crafting slot after breaking one block

### ISSUE THREAD

**Issue by CodingPenguin1** [zelythia/AutoTools#12]
On a 1.21 Realm, running Fabric

When a tool is switched to your hand, after you break one block, it'll go to your crafting slot

https://outplayed.tv/media/MwMyzg

**Comment by ValokAsura** [comment]
I'm having a similar issue, and it sometimes randomly throws my sword into my crafting slot when trying to mine barehanded. I've attached a couple of examples for reference.

https://youtu.be/P90ZA8lc_bs
https://youtu.be/x6nZjf2Novc

AutoTools Fabric 1.21 v2.1
Fabric 0.100.7+1.21
Fabric Loader 0.16.0

Thank you for the mod!

**Comment by kierkat10** [comment]
this happens to me also when it automatically switches to my shovel (because i'm digging dirt) with slabs in my hand. after one block, it just jumps into my crafting slot for seemingly no reason

**Comment by bideco** [comment]
I'm having this issue as well, it only seems to happen when I have the "Keep selected slot" option turned on. I like it on because then the new tool doesn't take up an extra slot on the hotbar but if it's going to throw my tool into the crafting grid every time I mine then it isn't worth it.

**Comment by kierkat10** [comment]
> I'm having this issue as well, it only seems to happen when I have the "Keep selected slot" option turned on. I like it on because then the new tool doesn't take up an extra slot on the hotbar but if it's going to throw my tool into the crafting grid every time I mine then it isn't worth it.

yeah, i just wish it was fixed lol

who knows, it could take 5 minutes or it could take 5 days.

**Comment by zelythia** [comment]
Hi, sorry for the late reply, but I finally got around to look at the problem. Turns out the fix was quite easy and it should be fixed in the next release of AutoTools

**Comment by kierkat10** [comment]
> Hi, sorry for the late reply, but I finally got around to look at the problem. Turns out the fix was quite easy and it should be fixed in the next release of AutoTools

yay!!

**Comment by LovelyLlama1** [comment]
This issue still perisits in fabric 1.21 since that version hasnt been updated yet. Is this update on the way?

**Comment by kierkat10** [comment]
> This issue still perisits in fabric 1.21 since that version hasnt been updated yet. Is this update on the way?

you can just use the 1.21.1 version, it works for 1.21 since 1.21.1 is such a minor update. that’s what i’ve been doing at least.
